### PR TITLE
Upgrade ember to 2.18

### LINKED ISSUE #28: DEPRECATION on 2.18
I've just recently resolved this same deprecation in another addon simply by upgrading ember, and found this one now as well.

DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/home/skidder/dev/brokermate/node_modules/ember-component-inbound-actions/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)

### PR DESCRIPTION
**Pull request by scottkidder**
Fixes #28

### CODE REVIEW

**Comment by GavinJoyce** [comment]
Thanks @scottkidder. It looks like CI is failing with

```
/home/travis/build/GavinJoyce/ember-component-inbound-actions/index.js
  3:1  error  'module' is not defined  no-undef
```

**Comment by GavinJoyce** [comment]
Thanks! Finally, perhaps you could squash down to a single commit before I merge?

**Comment by scottkidder** [comment]
squashed down. Thanks @GavinJoyce

**Comment by GavinJoyce** [comment]
Thanks @scottkidder

**Pull request merged**
